export const COLUMNAS_VISIBLES = {
  COMPONENTES_ACTIVO: [
    'codigo',
    'denominacion',
    'tipo',
    'creado',
    'modificado',
    'acciones',
  ],
  ASEGURADORAS: ['codigo', 'denominacion', 'creado', 'modificado', 'acciones'],
  CATEGORIAS: ['codigo', 'denominacion', 'creado', 'modificado', 'acciones'],
  CATEGORIAS_UNIDAD_ADMINISTRATIVA: [
    'codigo',
    'denominacion',
    'creado',
    'modificado',
    'acciones',
  ],
  CAUSAS_MOVIMIENTO: [
    'codigo',
    'denominacion',
    'tipo',
    'creado',
    'modificado',
    'acciones',
  ],
  CLASES: ['codigo', 'denominacion', 'creado', 'modificado', 'acciones'],
  COLORES: ['codigo', 'denominacion', 'creado', 'modificado', 'acciones'],
  COMPONENTES_ESTRUCTURA: [
    'codigo',
    'denominacion',
    'tipo',
    'creado',
    'modificado',
    'acciones',
  ],
  CONDICIONES_COMPRA: [
    'codigo',
    'denominacion',
    'creado',
    'modificado',
    'acciones',
  ],
  CONSERVACION: ['codigo', 'denominacion', 'creado', 'modificado', 'acciones'],
  ESTADOS_CONSERVACION: [
    'codigo',
    'denominacion',
    'creado',
    'modificado',
    'acciones',
  ],
  ESTADOS_USO: ['codigo', 'denominacion', 'creado', 'modificado', 'acciones'],
  MARCAS: [
    'codigo',
    'denominacion',
    'tipo',
    'creado',
    'modificado',
    'acciones',
  ],
  MODELOS: [
    'codigo',
    'denominacion',
    'marcaId',
    'creado',
    'modificado',
    'acciones',
  ],
  ORIGENES: ['codigo', 'modoAdquisicion', 'creado', 'modificado', 'acciones'],
  PROPOSITOS_SEMOVIENTE: [
    'codigo',
    'denominacion',
    'creado',
    'modificado',
    'acciones',
  ],
  RAZAS: ['codigo', 'denominacion', 'creado', 'modificado', 'acciones'],
  RESPONSABLES: [
    'tipo',
    'numeroCedula',
    'nombreCompleto',
    'cargo',
    'telefonos',
    'direccion',
    'correoElectronico',
    'creado',
    'modificado',
    'acciones',
  ],
  SEDES: ['codigo', 'denominacion', 'creado', 'modificado', 'acciones'],
  SEGUROS: ['codigo', 'denominacion', 'creado', 'modificado', 'acciones'],
  TIPOS_COBERTURA: [
    'codigo',
    'denominacion',
    'creado',
    'modificado',
    'acciones',
  ],
  TIPOS_COMPONENTE: [
    'codigo',
    'denominacion',
    'creado',
    'modificado',
    'acciones',
  ],
  TIPOS_ESTRUCTURA: [
    'codigo',
    'denominacion',
    'creado',
    'modificado',
    'acciones',
  ],
  TIPOS_MARCA: ['codigo', 'denominacion', 'creado', 'modificado', 'acciones'],
  TIPOS_POLIZA: ['codigo', 'denominacion', 'creado', 'modificado', 'acciones'],
  TIPOS_SEDE: ['codigo', 'denominacion', 'creado', 'modificado', 'acciones'],
  TIPOS_SEMOVIENTE: [
    'codigo',
    'denominacion',
    'creado',
    'modificado',
    'acciones',
  ],
  UNIDADES_ADMINISTRATIVAS: [
    'codigo',
    'denominacion',
    'creado',
    'modificado',
    'acciones',
  ],
  USOS: ['codigo', 'denominacion', 'creado', 'modificado', 'acciones'],
  ACTIVOS: ['codigo', 'denominacion', 'creado', 'modificado', 'acciones'],
};
