export const CORRELATIVOS: { nombre: string; id: number; tabla: string }[] = [
  { nombre: 'activo', id: 1, tabla: 'sbn_activos' },
  { nombre: 'activo - componente', id: 2, tabla: 'sbn_activos_componentes' },
  { nombre: 'aseguradora', id: 3, tabla: 'sbn_aseguradoras' },
  { nombre: 'catálogo general', id: 4, tabla: 'sbn_catalogo_general' },
  { nombre: 'categoría', id: 5, tabla: 'sbn_categorias' },
  {
    nombre: 'categoría de unidad administrativa',
    id: 6,
    tabla: 'sbn_categorias_unidad_administr',
  },
  { nombre: 'causa de movimiento', id: 7, tabla: 'sbn_causas_movimiento' },
  { nombre: 'clase', id: 8, tabla: 'sbn_clases' },
  { nombre: 'color', id: 9, tabla: 'sbn_colores' },
  {
    nombre: 'estado de conservación',
    id: 10,
    tabla: 'sbn_estados_conservacion',
  },
  { nombre: 'estado de uso', id: 11, tabla: 'sbn_estados_uso' },
  { nombre: 'marca', id: 12, tabla: 'sbn_marcas' },
  { nombre: 'modelo', id: 13, tabla: 'sbn_modelos' },
  { nombre: 'origen', id: 14, tabla: 'sbn_origenes' },
  {
    nombre: 'plantilla de depreciación',
    id: 15,
    tabla: 'sbn_plantillas_depreciacion',
  },
  {
    nombre: 'propósito semoviente',
    id: 16,
    tabla: 'sbn_propositos_semoviente',
  },
  { nombre: 'raza', id: 17, tabla: 'sbn_razas' },
  { nombre: 'rotulación', id: 18, tabla: 'sbn_rotulaciones' },
  { nombre: 'sede', id: 19, tabla: 'sbn_sedes' },
  { nombre: 'seguro', id: 20, tabla: 'sbn_seguros' },
  { nombre: 'tipo de animal', id: 21, tabla: 'sbn_tipos_animal' },
  { nombre: 'tipo de cobertura', id: 22, tabla: 'sbn_tipos_cobertura' },
  { nombre: 'tipo de componente', id: 23, tabla: 'sbn_tipos_componente' },
  { nombre: 'tipo de marca', id: 24, tabla: 'sbn_tipos_marca' },
  { nombre: 'tipo de póliza', id: 25, tabla: 'sbn_tipos_poliza' },
  { nombre: 'tipo de sede', id: 26, tabla: 'sbn_tipos_sede' },
  { nombre: 'tipo de semoviente', id: 27, tabla: 'sbn_tipos_semoviente' },
  { nombre: 'tipo de uso', id: 28, tabla: 'sbn_tipos_uso' },
  {
    nombre: 'unidad administrativa',
    id: 29,
    tabla: 'sbn_unidades_administrativas',
  },
  /*****************************/
  /** P  R  O  C  E  S  O  S  **/
  /*****************************/
  { nombre: 'acta de préstamo', id: 30, tabla: 'sbn_actas_prestamo' },
  {
    nombre: 'autorización de salida',
    id: 31,
    tabla: 'sbn_autorizaciones_salida',
  },
  {
    nombre: 'cambio de responsable',
    id: 32,
    tabla: 'sbn_cambios_responsable',
  },
  { nombre: 'depreciación', id: 33, tabla: 'sbn_depreciaciones' },
  {
    nombre: 'desincorporación',
    id: 34,
    tabla: 'sbn_desincorporaciones',
  },
  { nombre: 'entrega de unidad', id: 35, tabla: 'sbn_entregas_unidad' },
  { nombre: 'incorporación', id: 36, tabla: 'sbn_incorporaciones' },
  { nombre: 'modificación', id: 37, tabla: 'sbn_modificaciones' },
  { nombre: 'reasignación', id: 38, tabla: 'sbn_reasignaciones' },
  { nombre: 'retorno', id: 39, tabla: 'sbn_retornos' },
];
