export const END_POINTS: { clave: string; valor: string }[] = [
  { clave: 'activo', valor: 'dao/sbn/activo-dao.php' },
  { clave: 'aseguradoras', valor: 'dao/sbn/aseguradora-dao.php' },
  { clave: 'categoria', valor: 'dao/sbn/categoria-dao.php' },
  {
    clave: 'categoriaUnidadAdministrativa',
    valor: 'dao/sbn/categoria-unidad-administrativa-dao.php',
  },
  { clave: 'causaMovimiento', valor: 'dao/sbn/causa-movimiento-dao.php' },
  { clave: 'clase', valor: 'dao/sbn/clase-dao.php' },
  { clave: 'color', valor: 'dao/sbn/color-dao.php' },
  { clave: 'componenteActivo', valor: 'dao/sbn/componente-activo-dao.php' },
  {
    clave: 'componenteEstructura',
    valor: 'dao/sbn/componente-estructura-dao.php',
  },
  { clave: 'condicionCompra', valor: 'dao/sbn/condicion-compra-dao.php' },
  { clave: 'configuracion', valor: 'dao/sbn/configuracion-dao.php' },
  { clave: 'conservacion', valor: 'dao/sbn/conservacion-dao.php' },
  { clave: 'estadoUso', valor: 'dao/sbn/estado-uso-dao.php' },
  { clave: 'marca', valor: 'dao/sbn/marca-dao.php' },
  { clave: 'modelo', valor: 'dao/sbn/modelo-dao.php' },
  { clave: 'origen', valor: 'dao/sbn/origen-dao.php' },
  {
    clave: 'propositoSemoviente',
    valor: 'dao/sbn/proposito-semoviente-dao.php',
  },
  {
    clave: 'plantillaDepreciacion',
    valor: 'dao/sbn/plantilla-depreciacion-dao.php',
  },
  { clave: 'raza', valor: 'dao/sbn/raza-dao.php' },
  { clave: 'responsable', valor: 'dao/sbn/responsable-dao.php' },
  { clave: 'rotulacion', valor: 'dao/sbn/rotulacion-dao.php' },
  { clave: 'sede', valor: 'dao/sbn/sede-dao.php' },
  { clave: 'seguro', valor: 'dao/sbn/seguro-dao.php' },
  { clave: 'tipoCobertura', valor: 'dao/sbn/tipo-cobertura-dao.php' },
  { clave: 'tipoComponente', valor: 'dao/sbn/tipo-componente-dao.php' },
  { clave: 'tipoEstructura', valor: 'dao/sbn/tipo-estructura-dao.php' },
  { clave: 'tipoMarca', valor: 'dao/sbn/tipo-marca-dao.php' },
  { clave: 'tipoPoliza', valor: 'dao/sbn/tipo-poliza-dao.php' },
  { clave: 'tipoSede', valor: 'dao/sbn/tipo-sede-dao.php' },
  { clave: 'tipoSemoviente', valor: 'dao/sbn/tipo-semoviente-dao.php' },
  {
    clave: 'unidadAdministrativa',
    valor: 'dao/sbn/unidad-administrativa-dao.php',
  },
  { clave: 'uso', valor: 'sbn/dao/usos-dao.php' },
];
