export const END_POINTS: { clave: string; valor: string }[] = [
  { clave: 'activo', valor: 'activos' },
  { clave: 'activoComponent', valor: 'activos-component' },
  { clave: 'aseguradora', valor: 'aseguradoras' },
  {
    clave: 'categoriaUnidadAdministrativa',
    valor: 'categorias-unidad-administrativa',
  },
  { clave: 'categoria', valor: 'categorias' },
  { clave: 'causaMovimiento', valor: 'causas-movimiento' },
  { clave: 'clase', valor: 'clases' },
  { clave: 'color', valor: 'colores' },
  { clave: 'componenteEstructura', valor: 'componentes-estructura' },
  { clave: 'condicionCompra', valor: 'condiciones-compra' },
  { clave: 'conservacion', valor: 'conservaciones' },
  { clave: 'estadoUso', valor: 'estado-uso' },
  { clave: 'marca', valor: 'marcas' },
  { clave: 'modelo', valor: 'modelos' },
  { clave: 'origen', valor: 'origenes' },
  { clave: 'propositoSemoviente', valor: 'propositos-semoviente' },
  { clave: 'raza', valor: 'razas' },
  { clave: 'responsable', valor: 'responsables' },
  { clave: 'sede', valor: 'sedes' },
  { clave: 'seguro', valor: 'seguros' },
  { clave: 'tipoCobertura', valor: 'tipos-covertura' },
  { clave: 'tipoComponente', valor: 'tipos-componente' },
  { clave: 'tipoEstructura', valor: 'tipos-estructura' },
  { clave: 'tipoMarca', valor: 'tipos-marca' },
  { clave: 'tipoPoliza', valor: 'tipos-poliza' },
  { clave: 'tipoSede', valor: 'tipos-sede' },
  { clave: 'tipoSemoviente', valor: 'tipos-semoviente' },
  { clave: 'unidadAdministrativa', valor: 'unidades-administrativas' },
  { clave: 'uso', valor: 'usos' },
];
