export const END_POINTS: { clave: string; valor: string }[] = [
  /** definiciones */
  { clave: 'activo', valor: 'dao/sbn/activo-dao.php' },
  { clave: 'activoComponente', valor: 'dao/sbn/activo-componente-dao.php' },
  { clave: 'activoDepreciacion', valor: 'dao/sbn/activo-depreciacion-dao.php' },
  { clave: 'activoDetalle', valor: 'dao/sbn/activo-detalle-dao.php' },
  { clave: 'activoIntegracion', valor: 'dao/sbn/activo-integracion-dao.php' },
  { clave: 'activoUbicacion', valor: 'dao/sbn/activo-ubicacion-dao.php' },
  { clave: 'aseguradoras', valor: 'dao/sbn/aseguradora-dao.php' },
  { clave: 'catalogoGeneral', valor: 'dao/sbn/catalogo-general-dao.php' },
  { clave: 'categoria', valor: 'dao/sbn/categoria-dao.php' },
  {
    clave: 'categoriaUnidadAdministrativa',
    valor: 'dao/sbn/categoria-unidad-administrativa-dao.php',
  },
  { clave: 'causaMovimiento', valor: 'dao/sbn/causa-movimiento-dao.php' },
  { clave: 'clase', valor: 'dao/sbn/clase-dao.php' },
  { clave: 'color', valor: 'dao/sbn/color-dao.php' },
  { clave: 'componenteActivo', valor: 'dao/sbn/componente-activo-dao.php' },
  {
    clave: 'componenteEstructura',
    valor: 'dao/sbn/componente-estructura-dao.php',
  },
  { clave: 'condicionCompra', valor: 'dao/sbn/condicion-compra-dao.php' },
  { clave: 'configuracion', valor: 'dao/sbn/configuracion-dao.php' },
  { clave: 'estadoConservacion', valor: 'dao/sbn/estado-conservacion-dao.php' },
  { clave: 'correlativo', valor: 'dao/sbn/correlativo-dao.php' },
  { clave: 'estadoUso', valor: 'dao/sbn/estado-uso-dao.php' },
  { clave: 'marca', valor: 'dao/sbn/marca-dao.php' },
  { clave: 'modelo', valor: 'dao/sbn/modelo-dao.php' },
  { clave: 'origen', valor: 'dao/sbn/origen-dao.php' },
  {
    clave: 'propositoSemoviente',
    valor: 'dao/sbn/proposito-semoviente-dao.php',
  },
  {
    clave: 'plantillaIntegracion',
    valor: 'dao/sbn/plantilla-integracion-dao.php',
  },
  { clave: 'raza', valor: 'dao/sbn/raza-dao.php' },
  { clave: 'responsable', valor: 'dao/sbn/responsable-dao.php' },
  { clave: 'rotulacion', valor: 'dao/sbn/rotulacion-dao.php' },
  { clave: 'sede', valor: 'dao/sbn/sede-dao.php' },
  { clave: 'seguro', valor: 'dao/sbn/seguro-dao.php' },
  { clave: 'tipoAnimal', valor: 'dao/sbn/tipo-animal-dao.php' },
  { clave: 'tipoCobertura', valor: 'dao/sbn/tipo-cobertura-dao.php' },
  { clave: 'tipoComponente', valor: 'dao/sbn/tipo-componente-dao.php' },
  { clave: 'tipoEstructura', valor: 'dao/sbn/tipo-estructura-dao.php' },
  { clave: 'tipoMarca', valor: 'dao/sbn/tipo-marca-dao.php' },
  { clave: 'tipoPoliza', valor: 'dao/sbn/tipo-poliza-dao.php' },
  { clave: 'tipoSede', valor: 'dao/sbn/tipo-sede-dao.php' },
  { clave: 'tipoSemoviente', valor: 'dao/sbn/tipo-semoviente-dao.php' },
  {
    clave: 'unidadAdministrativa',
    valor: 'dao/sbn/unidad-administrativa-dao.php',
  },
  { clave: 'tipoUso', valor: 'dao/sbn/tipo-uso-dao.php' },

  /** procesos */
  { clave: 'actaPrestamo', valor: 'dao/sbn/acta-prestamo-dao.php' },
  {
    clave: 'actaPrestamoActivo',
    valor: 'dao/sbn/acta-prestamo-activo-dao.php',
  },
  { clave: 'autorizacionSalida', valor: 'dao/sbn/autorizacion-salida-dao.php' },
  {
    clave: 'autorizacionSalidaActivo',
    valor: 'dao/sbn/autorizacion-salida-activo-dao.php',
  },
  { clave: 'cambioResponsable', valor: 'dao/sbn/cambio-responsable-dao.php' },
  { clave: 'depreciacion', valor: 'dao/sbn/depreciacion-dao.php' },
  {
    clave: 'depreciacionDetalle',
    valor: 'dao/sbn/depreciacion-detalle-dao.php',
  },
  { clave: 'desincorporacion', valor: 'dao/sbn/desincorporacion-dao.php' },
  {
    clave: 'desincorporacionActivo',
    valor: 'dao/sbn/desincorporacion-activo-dao.php',
  },
  {
    clave: 'desincorporacionCuenta',
    valor: 'dao/sbn/desincorporacion-cuenta-dao.php',
  },
  { clave: 'entregaUnidad', valor: 'dao/sbn/entrega-unidad-dao.php' },
  { clave: 'incorporacion', valor: 'dao/sbn/incorporacion-dao.php' },
  {
    clave: 'incorporacionActivo',
    valor: 'dao/sbn/incorporacion-activo-dao.php',
  },
  { clave: 'modificacion', valor: 'dao/sbn/modificacion-dao.php' },
  {
    clave: 'modificacionCuenta',
    valor: 'dao/sbn/modificacion-cuenta-contable-dao.php',
  },
  {
    clave: 'modificacionComponente',
    valor: 'dao/sbn/modificacion-componente-dao.php',
  },
  { clave: 'reasignacion', valor: 'dao/sbn/reasignacion-dao.php' },
  { clave: 'reasignacionActivo', valor: 'dao/sbn/reasignacion-activo-dao.php' },
  { clave: 'retorno', valor: 'dao/sbn/retorno-dao.php' },
  { clave: 'retornoActivo', valor: 'dao/sbn/retorno-activo-dao.php' },
  { clave: 'unidadOrganizativa', valor: 'dao/sbn/unidad-organizativa-dao.php' },
  { clave: 'integracion', valor: 'dao/sbn/integracion-dao.php' },
];
