export const TIPOS_COMPROBANTE = [
  'ACTA DE PRESTAMO',
  'AUTORIZACIÓN DE SALIDA',
  'CAMBIO DE RESPONSABLE',
  'DEPRECIACIÓN',
  'DESINCORPORACIÓN',
  'ENTREGA DE UNIDAD',
  'INCORPORACIÓN',
  'MODIFICACIÓN',
  'REASIGNACIÓN',
  'RETORNO DE ACTIVO',
];
