export const UNIDADES_MEDIDA = {
  PESO: [
    'miligramos',
    'gramos',
    'kilogramos',
    'toneladas',
    'arrobas',
    'libras',
  ],
  TIEMPO: [
    // 'microsegundos',
    'milisegundos',
    'segundos',
    'minutos',
    'horas',
    'dias',
    'semanas',
    'quincenas',
    'meses',
    'trimestres',
    //'cuatrimestres',
    'semestres',
    'años',
    //'quinquenios',
    'decadas',
    'centenarios',
    'milenios',
    'eras',
  ],
};
