import { Basica } from '@core/models/basica';
import { Id } from '@core/types/id';

export interface Activo extends Basica {
  /* datos generales - incluye los datos de la interface basica*/
  codigo: string;
  denominacion: string;
  catalogoCuentas: string;
  tipoActivo: string;
  fechaAdquisicion: Date;
  fechaIngreso: Date;

  depreciable: boolean;
  observaciones: string;
  origenId: Id;
  unidadAdministrativaId: Id;
  sedeId: Id;
  peso: number;
  responsableUsoId: Id;
  estadoUsoId: Id;
  valorAdquisicion: number;
  monedaId: Id;
  conservacion: string;
  descripcionEstadoConservacion: Id;
  serial: string;
  marcaId: Id;
  modeloId: Id;
  anioFabricacion: number;
  poseeComponentes: boolean;
  descripcionComponente: string;
  especificacionesTecnicas: string;
  diasGarantia: number;
  fechaInicioGarantia: Date;
  fechaFinGarantia: Date;
  claseId: Id;
  descripcionOtraClase: string;
  serialCarroceria: string;
  serialMotor: string;
  placas: string;
  numeroTituloPropiedad: string;
  capacidad: string;
  nombre: string;
  usoId: string;
  tieneGPS: boolean;
  especificacionesGPS: string;
  tipoSemovienteId: string;
  genero: string;
  raza: string;
  propositoSemovienteId: string;
  unidadMedidaId: string;
  numeroHierro: string;
  numeroRegistro: string;
  fechaRegistro: string;
  popietarioAnterior: string;
  dependencias: string;
  areaConstruccionM2: string;
  areaTerrenoM2: string;
  especificacionesInmueble: string;
  perteneceASede: boolean;
  sedeUbicacionId: string;
  especificacionesColor: string;
  rotulacionId: string;
  categoriaId: string;
  tipoComponenteId: string;
  asegurado: boolean;
  seguroId: string;
  razaId: string;
  metodoDepreciacion: string;
  vidaUtil: string;
  valorRescate: number;
  cuentaContableGasto: string;
  cuentaContableDepreciacion: string;
  fuenteFinanciamientoId: string;
  codcencos: string;
}
