import { Id } from '@core/types/id';
import { Basica } from './basica';
import { Logico } from '@core/types/logico';

export interface ActivoDetalle extends Basica {
  activoId: Id;
  garantia: number;
  unidadGarantia: string;
  inicioGarantia: Date;
  finGarantia: Date;
  origenId: Id;
  asegurado: Logico;
  claseId: Id;
  descripcionOtraClase: string;
  fuenteFinanciamiento: string;
  codigoCentroCostos: string;
  especificacionesTecnicas: string;
  oficinaRegistro: string;
  referenciaRegistro: string;
  tomo: string;
  folio: string;
  protocolo: string;
  numeroRegistro: string;
  fechaRegistrado: Date;
  propietarioAnterior: string;
  dependencias: string;
  areaConstruccion: number;
  unidadAreaConstruccion: string;
  areaTerreno: number;
  unidadAreaTerreno: string;
  especificacionesInmueble: string;
  perteneceASede: Logico;
  sede_ubicacionId: Id;
  especificacionesColor: string;
  serialCarroceria: string;
  serialMotor: string;
  placas: string;
  numeroTituloPropiedad: string;
  capacidad: string;
  nombre: string;
  usoId: Id;
  tieneGps: Logico;
  especificacionesGps: string;
  tipoSemovienteId: Id;
  genero: string;
  propositoSemovienteId: Id;
  peso: number;
  unidadMedidaPeso: string;
  numeroHierro: string;
  especificacionesAnimal: string;
  tipoAnimalId: Id;
  fechaNacimientoAnimal: Date;
  razaId: Id;
}
