export type TipoProceso =
  | 'ACTA DE PRÉSTAMO'
  | 'AUTORIZACIÓN DE SALIDA'
  | 'CAMBIO DE RESPONSABLE'
  | 'DEPRECIACIÓN'
  | 'DESINCORPORACIÓN'
  | 'ENTREGA DE UNIDAD'
  | 'INCORPORACIÓN'
  | 'MODIFICACIÓN'
  | 'REASIGNACIÓN'
  | 'RETORNO';
