export type TipoProceso =
  | 'ACTA DE PRÉSTAMO DE ACTIVO'
  | 'AUTORIZACIÓN DE SALIDA DE ACTIVO'
  | 'CAMBIO DE RESPONSABLE DE ACTIVO'
  | 'DEPRECIACIÓN DE ACTIVO'
  | 'DESINCORPORACIÓN DE ACTIVO'
  | 'INCORPORACIÓN DE ACTIVO'
  | 'MODIFICACIÓN DE ACTIVO'
  | 'REASIGNACIÓN DE ACTIVO'
  | 'RETORNO DE ACTIVO';
