name: Compilar y Subir al Contabito
on:
  push:
    branches: 'main'
  pull_request:
    branches: 'main'
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true
jobs:
  compilar-subir:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: scp -o StrictHostKeyChecking=no -o PasswordAuthentication=yes -r .\dist\bienes ${{ secrets.CONTABITO_USER }}@${{ secrets.CONTABITO_HOST }}:/var/www/html/SigespERP/ <<< ${{ secrets.CONTABITO_PASSWORD }}
