name: Compilar y Subir al Contabito
on:
  push:
    branches: 'main'
  pull_request:
    branches: 'main'
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true
jobs:
  compilar-subir:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - name: Subir al Contabito via SCP- name: SSH Server Deploy
        uses: kostya-ten/ssh-server-deploy@v4
        with:
          host: ${{ secrets.CONTABITO_HOST }}
          port: ${{ secrets.CONTABITO_PORT }}
          username: ${{ secrets.CONTABITO_USER }}
          password: ${{ secrets.CONTABITO_PASSWORD }}
          scp_source: '/home/runner/work/sigesp_bienes/sigesp_bienes/dist/bienes/*'
          scp_target: '/var/www/html/SigespERP/bienes/'
          before_script: |
            df -h
          after_script: |
            whoami
        with:
